name: Schedule Probe

on:
  workflow_dispatch:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  probe:
    runs-on: ubuntu-latest
    steps:
      - name: Print time
        run: |
          echo "schedule probe"
          date -u
